// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/IASamoylov/tg_calories_observer/internal/clients/telegram (interfaces: TelegramAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	http "net/http"
	reflect "reflect"

	telegram "github.com/IASamoylov/tg_calories_observer/internal/clients/telegram"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockTelegramAPI is a mock of TelegramAPI interface.
type MockTelegramAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramAPIMockRecorder
}

// MockTelegramAPIMockRecorder is the mock recorder for MockTelegramAPI.
type MockTelegramAPIMockRecorder struct {
	mock *MockTelegramAPI
}

// NewMockTelegramAPI creates a new mock instance.
func NewMockTelegramAPI(ctrl *gomock.Controller) *MockTelegramAPI {
	mock := &MockTelegramAPI{ctrl: ctrl}
	mock.recorder = &MockTelegramAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramAPI) EXPECT() *MockTelegramAPIMockRecorder {
	return m.recorder
}

// CopyMessage mocks base method.
func (m *MockTelegramAPI) CopyMessage(arg0 tgbotapi.CopyMessageConfig) (tgbotapi.MessageID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyMessage", arg0)
	ret0, _ := ret[0].(tgbotapi.MessageID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyMessage indicates an expected call of CopyMessage.
func (mr *MockTelegramAPIMockRecorder) CopyMessage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyMessage", reflect.TypeOf((*MockTelegramAPI)(nil).CopyMessage), arg0)
}

// GetChat mocks base method.
func (m *MockTelegramAPI) GetChat(arg0 tgbotapi.ChatInfoConfig) (tgbotapi.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", arg0)
	ret0, _ := ret[0].(tgbotapi.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockTelegramAPIMockRecorder) GetChat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockTelegramAPI)(nil).GetChat), arg0)
}

// GetChatAdministrators mocks base method.
func (m *MockTelegramAPI) GetChatAdministrators(arg0 tgbotapi.ChatAdministratorsConfig) ([]tgbotapi.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatAdministrators", arg0)
	ret0, _ := ret[0].([]tgbotapi.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatAdministrators indicates an expected call of GetChatAdministrators.
func (mr *MockTelegramAPIMockRecorder) GetChatAdministrators(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatAdministrators", reflect.TypeOf((*MockTelegramAPI)(nil).GetChatAdministrators), arg0)
}

// GetChatMember mocks base method.
func (m *MockTelegramAPI) GetChatMember(arg0 tgbotapi.GetChatMemberConfig) (tgbotapi.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMember", arg0)
	ret0, _ := ret[0].(tgbotapi.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMember indicates an expected call of GetChatMember.
func (mr *MockTelegramAPIMockRecorder) GetChatMember(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMember", reflect.TypeOf((*MockTelegramAPI)(nil).GetChatMember), arg0)
}

// GetChatMembersCount mocks base method.
func (m *MockTelegramAPI) GetChatMembersCount(arg0 tgbotapi.ChatMemberCountConfig) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembersCount", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembersCount indicates an expected call of GetChatMembersCount.
func (mr *MockTelegramAPIMockRecorder) GetChatMembersCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembersCount", reflect.TypeOf((*MockTelegramAPI)(nil).GetChatMembersCount), arg0)
}

// GetFile mocks base method.
func (m *MockTelegramAPI) GetFile(arg0 tgbotapi.FileConfig) (tgbotapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", arg0)
	ret0, _ := ret[0].(tgbotapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockTelegramAPIMockRecorder) GetFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockTelegramAPI)(nil).GetFile), arg0)
}

// GetFileDirectURL mocks base method.
func (m *MockTelegramAPI) GetFileDirectURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileDirectURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileDirectURL indicates an expected call of GetFileDirectURL.
func (mr *MockTelegramAPIMockRecorder) GetFileDirectURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileDirectURL", reflect.TypeOf((*MockTelegramAPI)(nil).GetFileDirectURL), arg0)
}

// GetGameHighScores mocks base method.
func (m *MockTelegramAPI) GetGameHighScores(arg0 tgbotapi.GetGameHighScoresConfig) ([]tgbotapi.GameHighScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameHighScores", arg0)
	ret0, _ := ret[0].([]tgbotapi.GameHighScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameHighScores indicates an expected call of GetGameHighScores.
func (mr *MockTelegramAPIMockRecorder) GetGameHighScores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameHighScores", reflect.TypeOf((*MockTelegramAPI)(nil).GetGameHighScores), arg0)
}

// GetInviteLink mocks base method.
func (m *MockTelegramAPI) GetInviteLink(arg0 tgbotapi.ChatInviteLinkConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteLink", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteLink indicates an expected call of GetInviteLink.
func (mr *MockTelegramAPIMockRecorder) GetInviteLink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteLink", reflect.TypeOf((*MockTelegramAPI)(nil).GetInviteLink), arg0)
}

// GetMe mocks base method.
func (m *MockTelegramAPI) GetMe() (tgbotapi.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe")
	ret0, _ := ret[0].(tgbotapi.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockTelegramAPIMockRecorder) GetMe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockTelegramAPI)(nil).GetMe))
}

// GetMyCommands mocks base method.
func (m *MockTelegramAPI) GetMyCommands() ([]tgbotapi.BotCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyCommands")
	ret0, _ := ret[0].([]tgbotapi.BotCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyCommands indicates an expected call of GetMyCommands.
func (mr *MockTelegramAPIMockRecorder) GetMyCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyCommands", reflect.TypeOf((*MockTelegramAPI)(nil).GetMyCommands))
}

// GetMyCommandsWithConfig mocks base method.
func (m *MockTelegramAPI) GetMyCommandsWithConfig(arg0 tgbotapi.GetMyCommandsConfig) ([]tgbotapi.BotCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyCommandsWithConfig", arg0)
	ret0, _ := ret[0].([]tgbotapi.BotCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyCommandsWithConfig indicates an expected call of GetMyCommandsWithConfig.
func (mr *MockTelegramAPIMockRecorder) GetMyCommandsWithConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyCommandsWithConfig", reflect.TypeOf((*MockTelegramAPI)(nil).GetMyCommandsWithConfig), arg0)
}

// GetStickerSet mocks base method.
func (m *MockTelegramAPI) GetStickerSet(arg0 tgbotapi.GetStickerSetConfig) (tgbotapi.StickerSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerSet", arg0)
	ret0, _ := ret[0].(tgbotapi.StickerSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerSet indicates an expected call of GetStickerSet.
func (mr *MockTelegramAPIMockRecorder) GetStickerSet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerSet", reflect.TypeOf((*MockTelegramAPI)(nil).GetStickerSet), arg0)
}

// GetUpdates mocks base method.
func (m *MockTelegramAPI) GetUpdates(arg0 tgbotapi.UpdateConfig) ([]tgbotapi.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdates", arg0)
	ret0, _ := ret[0].([]tgbotapi.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdates indicates an expected call of GetUpdates.
func (mr *MockTelegramAPIMockRecorder) GetUpdates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdates", reflect.TypeOf((*MockTelegramAPI)(nil).GetUpdates), arg0)
}

// GetUpdatesChan mocks base method.
func (m *MockTelegramAPI) GetUpdatesChan(arg0 tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", arg0)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockTelegramAPIMockRecorder) GetUpdatesChan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockTelegramAPI)(nil).GetUpdatesChan), arg0)
}

// GetUserProfilePhotos mocks base method.
func (m *MockTelegramAPI) GetUserProfilePhotos(arg0 tgbotapi.UserProfilePhotosConfig) (tgbotapi.UserProfilePhotos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfilePhotos", arg0)
	ret0, _ := ret[0].(tgbotapi.UserProfilePhotos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfilePhotos indicates an expected call of GetUserProfilePhotos.
func (mr *MockTelegramAPIMockRecorder) GetUserProfilePhotos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfilePhotos", reflect.TypeOf((*MockTelegramAPI)(nil).GetUserProfilePhotos), arg0)
}

// GetWebhookInfo mocks base method.
func (m *MockTelegramAPI) GetWebhookInfo() (tgbotapi.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookInfo")
	ret0, _ := ret[0].(tgbotapi.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookInfo indicates an expected call of GetWebhookInfo.
func (mr *MockTelegramAPIMockRecorder) GetWebhookInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookInfo", reflect.TypeOf((*MockTelegramAPI)(nil).GetWebhookInfo))
}

// HandleUpdate mocks base method.
func (m *MockTelegramAPI) HandleUpdate(arg0 *http.Request) (*tgbotapi.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate", arg0)
	ret0, _ := ret[0].(*tgbotapi.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockTelegramAPIMockRecorder) HandleUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockTelegramAPI)(nil).HandleUpdate), arg0)
}

// IsMessageToMe mocks base method.
func (m *MockTelegramAPI) IsMessageToMe(arg0 telegram.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMessageToMe", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMessageToMe indicates an expected call of IsMessageToMe.
func (mr *MockTelegramAPIMockRecorder) IsMessageToMe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMessageToMe", reflect.TypeOf((*MockTelegramAPI)(nil).IsMessageToMe), arg0)
}

// ListenForWebhook mocks base method.
func (m *MockTelegramAPI) ListenForWebhook(arg0 string) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForWebhook", arg0)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// ListenForWebhook indicates an expected call of ListenForWebhook.
func (mr *MockTelegramAPIMockRecorder) ListenForWebhook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForWebhook", reflect.TypeOf((*MockTelegramAPI)(nil).ListenForWebhook), arg0)
}

// ListenForWebhookRespReqFormat mocks base method.
func (m *MockTelegramAPI) ListenForWebhookRespReqFormat(arg0 http.ResponseWriter, arg1 *http.Request) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForWebhookRespReqFormat", arg0, arg1)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// ListenForWebhookRespReqFormat indicates an expected call of ListenForWebhookRespReqFormat.
func (mr *MockTelegramAPIMockRecorder) ListenForWebhookRespReqFormat(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForWebhookRespReqFormat", reflect.TypeOf((*MockTelegramAPI)(nil).ListenForWebhookRespReqFormat), arg0, arg1)
}

// MakeRequest mocks base method.
func (m *MockTelegramAPI) MakeRequest(arg0 string, arg1 tgbotapi.Params) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequest", arg0, arg1)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequest indicates an expected call of MakeRequest.
func (mr *MockTelegramAPIMockRecorder) MakeRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockTelegramAPI)(nil).MakeRequest), arg0, arg1)
}

// Request mocks base method.
func (m *MockTelegramAPI) Request(arg0 tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", arg0)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockTelegramAPIMockRecorder) Request(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockTelegramAPI)(nil).Request), arg0)
}

// Send mocks base method.
func (m *MockTelegramAPI) Send(arg0 tgbotapi.Chattable) (telegram.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(telegram.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTelegramAPIMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTelegramAPI)(nil).Send), arg0)
}

// SendMediaGroup mocks base method.
func (m *MockTelegramAPI) SendMediaGroup(arg0 tgbotapi.MediaGroupConfig) ([]telegram.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMediaGroup", arg0)
	ret0, _ := ret[0].([]telegram.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMediaGroup indicates an expected call of SendMediaGroup.
func (mr *MockTelegramAPIMockRecorder) SendMediaGroup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMediaGroup", reflect.TypeOf((*MockTelegramAPI)(nil).SendMediaGroup), arg0)
}

// SetAPIEndpoint mocks base method.
func (m *MockTelegramAPI) SetAPIEndpoint(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAPIEndpoint", arg0)
}

// SetAPIEndpoint indicates an expected call of SetAPIEndpoint.
func (mr *MockTelegramAPIMockRecorder) SetAPIEndpoint(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPIEndpoint", reflect.TypeOf((*MockTelegramAPI)(nil).SetAPIEndpoint), arg0)
}

// StopPoll mocks base method.
func (m *MockTelegramAPI) StopPoll(arg0 tgbotapi.StopPollConfig) (tgbotapi.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopPoll", arg0)
	ret0, _ := ret[0].(tgbotapi.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopPoll indicates an expected call of StopPoll.
func (mr *MockTelegramAPIMockRecorder) StopPoll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopPoll", reflect.TypeOf((*MockTelegramAPI)(nil).StopPoll), arg0)
}

// StopReceivingUpdates mocks base method.
func (m *MockTelegramAPI) StopReceivingUpdates() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopReceivingUpdates")
}

// StopReceivingUpdates indicates an expected call of StopReceivingUpdates.
func (mr *MockTelegramAPIMockRecorder) StopReceivingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopReceivingUpdates", reflect.TypeOf((*MockTelegramAPI)(nil).StopReceivingUpdates))
}

// UploadFiles mocks base method.
func (m *MockTelegramAPI) UploadFiles(arg0 string, arg1 tgbotapi.Params, arg2 []tgbotapi.RequestFile) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFiles", arg0, arg1, arg2)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockTelegramAPIMockRecorder) UploadFiles(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockTelegramAPI)(nil).UploadFiles), arg0, arg1, arg2)
}

// decodeAPIResponse mocks base method.
func (m *MockTelegramAPI) decodeAPIResponse(arg0 io.Reader, arg1 *tgbotapi.APIResponse) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decodeAPIResponse", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// decodeAPIResponse indicates an expected call of decodeAPIResponse.
func (mr *MockTelegramAPIMockRecorder) decodeAPIResponse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decodeAPIResponse", reflect.TypeOf((*MockTelegramAPI)(nil).decodeAPIResponse), arg0, arg1)
}
