// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/IASamoylov/tg_calories_observer/internal/clients/telegram (interfaces: BotAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockBotAPI is a mock of BotAPI interface.
type MockBotAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBotAPIMockRecorder
}

// MockBotAPIMockRecorder is the mock recorder for MockBotAPI.
type MockBotAPIMockRecorder struct {
	mock *MockBotAPI
}

// NewMockBotAPI creates a new mock instance.
func NewMockBotAPI(ctrl *gomock.Controller) *MockBotAPI {
	mock := &MockBotAPI{ctrl: ctrl}
	mock.recorder = &MockBotAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotAPI) EXPECT() *MockBotAPIMockRecorder {
	return m.recorder
}

// CopyMessage mocks base method.
func (m *MockBotAPI) CopyMessage(arg0 tgbotapi.CopyMessageConfig) (tgbotapi.MessageID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyMessage", arg0)
	ret0, _ := ret[0].(tgbotapi.MessageID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyMessage indicates an expected call of CopyMessage.
func (mr *MockBotAPIMockRecorder) CopyMessage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyMessage", reflect.TypeOf((*MockBotAPI)(nil).CopyMessage), arg0)
}

// GetChat mocks base method.
func (m *MockBotAPI) GetChat(arg0 tgbotapi.ChatInfoConfig) (tgbotapi.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", arg0)
	ret0, _ := ret[0].(tgbotapi.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockBotAPIMockRecorder) GetChat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockBotAPI)(nil).GetChat), arg0)
}

// GetChatAdministrators mocks base method.
func (m *MockBotAPI) GetChatAdministrators(arg0 tgbotapi.ChatAdministratorsConfig) ([]tgbotapi.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatAdministrators", arg0)
	ret0, _ := ret[0].([]tgbotapi.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatAdministrators indicates an expected call of GetChatAdministrators.
func (mr *MockBotAPIMockRecorder) GetChatAdministrators(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatAdministrators", reflect.TypeOf((*MockBotAPI)(nil).GetChatAdministrators), arg0)
}

// GetChatMember mocks base method.
func (m *MockBotAPI) GetChatMember(arg0 tgbotapi.GetChatMemberConfig) (tgbotapi.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMember", arg0)
	ret0, _ := ret[0].(tgbotapi.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMember indicates an expected call of GetChatMember.
func (mr *MockBotAPIMockRecorder) GetChatMember(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMember", reflect.TypeOf((*MockBotAPI)(nil).GetChatMember), arg0)
}

// GetChatMembersCount mocks base method.
func (m *MockBotAPI) GetChatMembersCount(arg0 tgbotapi.ChatMemberCountConfig) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembersCount", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembersCount indicates an expected call of GetChatMembersCount.
func (mr *MockBotAPIMockRecorder) GetChatMembersCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembersCount", reflect.TypeOf((*MockBotAPI)(nil).GetChatMembersCount), arg0)
}

// GetFile mocks base method.
func (m *MockBotAPI) GetFile(arg0 tgbotapi.FileConfig) (tgbotapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", arg0)
	ret0, _ := ret[0].(tgbotapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockBotAPIMockRecorder) GetFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockBotAPI)(nil).GetFile), arg0)
}

// GetFileDirectURL mocks base method.
func (m *MockBotAPI) GetFileDirectURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileDirectURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileDirectURL indicates an expected call of GetFileDirectURL.
func (mr *MockBotAPIMockRecorder) GetFileDirectURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileDirectURL", reflect.TypeOf((*MockBotAPI)(nil).GetFileDirectURL), arg0)
}

// GetGameHighScores mocks base method.
func (m *MockBotAPI) GetGameHighScores(arg0 tgbotapi.GetGameHighScoresConfig) ([]tgbotapi.GameHighScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameHighScores", arg0)
	ret0, _ := ret[0].([]tgbotapi.GameHighScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameHighScores indicates an expected call of GetGameHighScores.
func (mr *MockBotAPIMockRecorder) GetGameHighScores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameHighScores", reflect.TypeOf((*MockBotAPI)(nil).GetGameHighScores), arg0)
}

// GetInviteLink mocks base method.
func (m *MockBotAPI) GetInviteLink(arg0 tgbotapi.ChatInviteLinkConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteLink", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteLink indicates an expected call of GetInviteLink.
func (mr *MockBotAPIMockRecorder) GetInviteLink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteLink", reflect.TypeOf((*MockBotAPI)(nil).GetInviteLink), arg0)
}

// GetMe mocks base method.
func (m *MockBotAPI) GetMe() (tgbotapi.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe")
	ret0, _ := ret[0].(tgbotapi.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockBotAPIMockRecorder) GetMe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockBotAPI)(nil).GetMe))
}

// GetMyCommands mocks base method.
func (m *MockBotAPI) GetMyCommands() ([]tgbotapi.BotCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyCommands")
	ret0, _ := ret[0].([]tgbotapi.BotCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyCommands indicates an expected call of GetMyCommands.
func (mr *MockBotAPIMockRecorder) GetMyCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyCommands", reflect.TypeOf((*MockBotAPI)(nil).GetMyCommands))
}

// GetMyCommandsWithConfig mocks base method.
func (m *MockBotAPI) GetMyCommandsWithConfig(arg0 tgbotapi.GetMyCommandsConfig) ([]tgbotapi.BotCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyCommandsWithConfig", arg0)
	ret0, _ := ret[0].([]tgbotapi.BotCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyCommandsWithConfig indicates an expected call of GetMyCommandsWithConfig.
func (mr *MockBotAPIMockRecorder) GetMyCommandsWithConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyCommandsWithConfig", reflect.TypeOf((*MockBotAPI)(nil).GetMyCommandsWithConfig), arg0)
}

// GetStickerSet mocks base method.
func (m *MockBotAPI) GetStickerSet(arg0 tgbotapi.GetStickerSetConfig) (tgbotapi.StickerSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerSet", arg0)
	ret0, _ := ret[0].(tgbotapi.StickerSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerSet indicates an expected call of GetStickerSet.
func (mr *MockBotAPIMockRecorder) GetStickerSet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerSet", reflect.TypeOf((*MockBotAPI)(nil).GetStickerSet), arg0)
}

// GetUpdates mocks base method.
func (m *MockBotAPI) GetUpdates(arg0 tgbotapi.UpdateConfig) ([]tgbotapi.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdates", arg0)
	ret0, _ := ret[0].([]tgbotapi.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdates indicates an expected call of GetUpdates.
func (mr *MockBotAPIMockRecorder) GetUpdates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdates", reflect.TypeOf((*MockBotAPI)(nil).GetUpdates), arg0)
}

// GetUpdatesChan mocks base method.
func (m *MockBotAPI) GetUpdatesChan(arg0 tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", arg0)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockBotAPIMockRecorder) GetUpdatesChan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockBotAPI)(nil).GetUpdatesChan), arg0)
}

// GetUserProfilePhotos mocks base method.
func (m *MockBotAPI) GetUserProfilePhotos(arg0 tgbotapi.UserProfilePhotosConfig) (tgbotapi.UserProfilePhotos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfilePhotos", arg0)
	ret0, _ := ret[0].(tgbotapi.UserProfilePhotos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfilePhotos indicates an expected call of GetUserProfilePhotos.
func (mr *MockBotAPIMockRecorder) GetUserProfilePhotos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfilePhotos", reflect.TypeOf((*MockBotAPI)(nil).GetUserProfilePhotos), arg0)
}

// GetWebhookInfo mocks base method.
func (m *MockBotAPI) GetWebhookInfo() (tgbotapi.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookInfo")
	ret0, _ := ret[0].(tgbotapi.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookInfo indicates an expected call of GetWebhookInfo.
func (mr *MockBotAPIMockRecorder) GetWebhookInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookInfo", reflect.TypeOf((*MockBotAPI)(nil).GetWebhookInfo))
}

// HandleUpdate mocks base method.
func (m *MockBotAPI) HandleUpdate(arg0 *http.Request) (*tgbotapi.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate", arg0)
	ret0, _ := ret[0].(*tgbotapi.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockBotAPIMockRecorder) HandleUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockBotAPI)(nil).HandleUpdate), arg0)
}

// IsMessageToMe mocks base method.
func (m *MockBotAPI) IsMessageToMe(arg0 tgbotapi.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMessageToMe", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMessageToMe indicates an expected call of IsMessageToMe.
func (mr *MockBotAPIMockRecorder) IsMessageToMe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMessageToMe", reflect.TypeOf((*MockBotAPI)(nil).IsMessageToMe), arg0)
}

// ListenForWebhook mocks base method.
func (m *MockBotAPI) ListenForWebhook(arg0 string) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForWebhook", arg0)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// ListenForWebhook indicates an expected call of ListenForWebhook.
func (mr *MockBotAPIMockRecorder) ListenForWebhook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForWebhook", reflect.TypeOf((*MockBotAPI)(nil).ListenForWebhook), arg0)
}

// ListenForWebhookRespReqFormat mocks base method.
func (m *MockBotAPI) ListenForWebhookRespReqFormat(arg0 http.ResponseWriter, arg1 *http.Request) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForWebhookRespReqFormat", arg0, arg1)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// ListenForWebhookRespReqFormat indicates an expected call of ListenForWebhookRespReqFormat.
func (mr *MockBotAPIMockRecorder) ListenForWebhookRespReqFormat(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForWebhookRespReqFormat", reflect.TypeOf((*MockBotAPI)(nil).ListenForWebhookRespReqFormat), arg0, arg1)
}

// MakeRequest mocks base method.
func (m *MockBotAPI) MakeRequest(arg0 string, arg1 tgbotapi.Params) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequest", arg0, arg1)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequest indicates an expected call of MakeRequest.
func (mr *MockBotAPIMockRecorder) MakeRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockBotAPI)(nil).MakeRequest), arg0, arg1)
}

// Request mocks base method.
func (m *MockBotAPI) Request(arg0 tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", arg0)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockBotAPIMockRecorder) Request(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockBotAPI)(nil).Request), arg0)
}

// Send mocks base method.
func (m *MockBotAPI) Send(arg0 tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockBotAPIMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBotAPI)(nil).Send), arg0)
}

// SendMediaGroup mocks base method.
func (m *MockBotAPI) SendMediaGroup(arg0 tgbotapi.MediaGroupConfig) ([]tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMediaGroup", arg0)
	ret0, _ := ret[0].([]tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMediaGroup indicates an expected call of SendMediaGroup.
func (mr *MockBotAPIMockRecorder) SendMediaGroup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMediaGroup", reflect.TypeOf((*MockBotAPI)(nil).SendMediaGroup), arg0)
}

// SetAPIEndpoint mocks base method.
func (m *MockBotAPI) SetAPIEndpoint(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAPIEndpoint", arg0)
}

// SetAPIEndpoint indicates an expected call of SetAPIEndpoint.
func (mr *MockBotAPIMockRecorder) SetAPIEndpoint(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPIEndpoint", reflect.TypeOf((*MockBotAPI)(nil).SetAPIEndpoint), arg0)
}

// StopPoll mocks base method.
func (m *MockBotAPI) StopPoll(arg0 tgbotapi.StopPollConfig) (tgbotapi.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopPoll", arg0)
	ret0, _ := ret[0].(tgbotapi.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopPoll indicates an expected call of StopPoll.
func (mr *MockBotAPIMockRecorder) StopPoll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopPoll", reflect.TypeOf((*MockBotAPI)(nil).StopPoll), arg0)
}

// StopReceivingUpdates mocks base method.
func (m *MockBotAPI) StopReceivingUpdates() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopReceivingUpdates")
}

// StopReceivingUpdates indicates an expected call of StopReceivingUpdates.
func (mr *MockBotAPIMockRecorder) StopReceivingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopReceivingUpdates", reflect.TypeOf((*MockBotAPI)(nil).StopReceivingUpdates))
}

// UploadFiles mocks base method.
func (m *MockBotAPI) UploadFiles(arg0 string, arg1 tgbotapi.Params, arg2 []tgbotapi.RequestFile) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFiles", arg0, arg1, arg2)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockBotAPIMockRecorder) UploadFiles(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockBotAPI)(nil).UploadFiles), arg0, arg1, arg2)
}
