name: Set environment variables

description: Configures environment variables for a workflow
inputs:
  file:
    description: File path to variable file or directory
    required: true
  comit:
    description: sha
    required: true
runs:
  using: composite
  steps:
    - run: |
        BUILD_SHA=${{ inputs.comit }}
        echo "BUILD_SHA_SHORT=$(echo ${BUILD_SHA} | cut -c 1-8)" >> $GITHUB_ENV
        echo "BUILD_SHA=${BUILD_SHA}" >> $GITHUB_ENV
        cat ${{ inputs.file }} >> ${GITHUB_ENV}
      shell: bash
