name: Checkout and set environment variables

description: Checkout with pre-installed env variables
inputs:
  file:
    description: File path to variable file or directory
    required: true
runs:
  using: composite
  steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/set_environment_variables
      with:
        file: ${{ inputs.file }}
