version: "3.9"
name: ${APP_NAME}-infra
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust # docker-compose are using only for dev/integration tests
    ports:
      - "5432:5432"
