name: Set environment variables

description: Configures environment variables for a workflow
inputs:
  image-tag:
    description: Setup build image tag
    required: true
runs:
  using: composite
  steps:
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CONTAINER_REGISTRY: ${{ secrets.YC_CR_ID }
        APP_VERSION: ${{ env.GITHUB_SHA_SHORT }}
      run: |
        make build-docker
        make push-docker
      shell: bash
