# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, Publish & Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      checks: write
      pull-requests: write
    secrets: inherit

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yaml
    with:
      ref: ${{ env.GITHUB_SHA }}
    secrets: inherit

  deployment:
    name: Deploy
    if: ${{ github.ref_name == 'release' || github.ref_name == 'release/*' }}
    needs:
      - publish
    uses: ./.github/workflows/deploy.yaml
    with:
      target: "Beta"
      tag: ${{ needs.publish.outputs.GITHUB_SHA_SHORT }}
      revision-core-fraction: 5
      suffix: "-beta"
      container-name: ${{ needs.publish.outputs.APP_NAME }}
    secrets: inherit

  release:
    name: Create relase
    needs:
      - build
      - publish
      - deployment
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.GITHUB_ACTOR }}
          minimum-approvals: 1
          issue-title: "Approve before to close release"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d%H%M')"
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Release v${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          create-release: ${{ needs.publish.outputs.GITHUB_SHA_SHORT }}
