# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, Publish & Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      checks: write
      pull-requests: write
    secrets: inherit

  publish:
    name: Publish
    needs: build
    if: ${{ github.ref_name == 'release' || github.ref_name == 'release/*' }}
    uses: ./.github/workflows/publish.yaml
    with:
      ref: ${{ github.GITHUB_SHA }}
    secrets: inherit

  deployment:
    name: Deploy
    needs: publish
    uses: ./.github/workflows/deploy.yaml
    with:
      target: "Beta"
      tag: ${{ needs.publish.outputs.GITHUB_SHA_SHORT }}
      revision-core-fraction: 5
      suffix: "-beta"
      container-name: ${{ needs.publish.outputs.APP_NAME }}
    secrets: inherit

  release:
    name: Create relase
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secret.MYPAT }}
    needs:
      - deployment
    runs-on: ubuntu-latest
    environment: "Beta"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d%H%M')"
      - name: Create tag
        run: |
          git tag v${{ steps.date.outputs.date }} ${{ github.GITHUB_SHA }}
          git push origin v${{ steps.date.outputs.date }}
