name: Deploy to
run-name: Release to ${{ inputs.target }} of ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: >
          The branch, tag or SHA to checkout, publish and deploy image. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that
          event. Otherwise, uses the default branch.
        type: string
      target:
        description: "Environment to deploy"
        type: environment
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      IMAGE_EXIST: ${{ steps.iamge_exist.outputs.IMAGE_EXIST }}
    env:
      BUILD_SHA: ${{ !!inputs.ref && inputs.ref || github.sha }}
      BUILD_SHA_TEST: ${{ inputs.ref && '124' || '421' }}
    steps:
      - run: |
          echo "🎉 ref ${{ inputs.ref }}"
          echo "🎉 build sha test ${{ env.BUILD_SHA_TEST }}"
          echo "🎉 build sha ${{ env.BUILD_SHA }}"
          echo "🎉 github sha ${{ github.sha }}"
          echo "BUILD_SHA_SHORT=$(echo $BUILD_SHA | cut -c 1-8)" >> $GITHUB_ENV
          echo "🎉 github sha short ${{env.BUILD_SHA_SHORT}}"
  # deployment:
  #   name: ${{ inputs.target }}
  #   uses: ./.github/workflows/deploy.yaml
  #   with:
  #     target: ${{ inputs.target }}
  #     ref: ${{ inputs.ref }}
  #   secrets: inherit
