name: Deploy to ${{ inputs.target }}
run-name: Release to ${{ inputs.target }} of ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: >
          The branch, tag or SHA to checkout, publish and deploy image. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that
          event. Otherwise, uses the default branch.
        type: string
      target:
        description: "Environment to deploy"
        type: environment
        required: true

jobs:
  deployment:
    name: Deploy / ${{ inputs.target }}
    needs:
      - tag
      - publish
    uses: ./.github/workflows/deploy.yaml
    with:
      target: ${{ inputs.target }}
      ref: ${{ inputs.ref }}
    secrets: inherit
