name: Deployment workflow

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Branch, tag or SHA
      IS_LATEST:
        type: boolean
        description: Is latest build and push
        default: false
      APP_VERSION:
        type: string
        description: Tag
    secrets:
      YC_SA_JSON_CREDENTIALS:
        required: true
      YC_CR_ID:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 publish ref ${{ inputs.ref }}"
      - name: Setup Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Set Environment Variables
        uses: ./.github/actions/set_environment_variables
        with:
          file: ./.build/.env
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build and push image to Yandex Cloud Container Registry
        env:
          CONTAINER_REGISTRY: ${{ secrets.YC_CR_ID }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
        run: |
          make build-docker
          make push-docker
      - name: Add specific tag
        if: ${{ inputs.IS_LATEST }}
        run: |
          docker tag ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:${{env.GITHUB_SHA_SHORT}} ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:latest
          docker push ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:latest
