name: Deployment workflow

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Branch, tag or SHA
      tag:
        type: string
        description: Tag
    outputs:
      GITHUB_SHA_SHORT:
        value: ${{ jobs.publish.outputs.GITHUB_SHA_SHORT }}
      APP_NAME:
        value: ${{ jobs.publish.outputs.APP_NAME }}
    secrets:
      YC_SA_JSON_CREDENTIALS:
        required: true
      YC_CR_ID:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    outputs:
      GITHUB_SHA_SHORT: ${{ steps.output_tag.outputs.GITHUB_SHA_SHORT }}
      APP_NAME: ${{ steps.output_tag.outputs.APP_NAME }}
    steps:
      - run: echo "🎉 publish ref ${{ inputs.ref }}"
      - name: Setup Checkout
        uses: actions/checkout@v3
        with:
          ref: ""
      - name: Set Environment Variables
        uses: ./.github/actions/set_environment_variables
        with:
          file: ./.build/.env
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build and push image to Yandex Cloud Container Registry
        env:
          CONTAINER_REGISTRY: ${{ secrets.YC_CR_ID }}
        run: |
          make build-docker
          make push-docker
      - name: Add specific tag
        if: ${{ !!inputs.tag }}
        run: |
          docker tag ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:${{env.GITHUB_SHA_SHORT}} ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:${{inputs.tag}}
          docker push ${{ secrets.YC_CR_ID }}${{ env.APP_NAME }}:${{inputs.tag}}
      - name: Output tag
        id: output_tag
        run: |
          echo "GITHUB_SHA_SHORT=${{env.GITHUB_SHA_SHORT}}" >> $GITHUB_OUTPUT
          echo "APP_NAME=${{env.APP_NAME}}" >> $GITHUB_OUTPUT
