# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, Tests & Reports

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      checks: write
      pull-requests: write
    secrets: inherit
