name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"

jobs:
  checkout:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: ./.github/actions/set_environment_variables
        with:
          file: ./.build/.env

  deployment:
    name: Deploy
    needs:
      - checkout
    uses: ./.github/workflows/deploy.yaml
    with:
      target: "Production"
      tag: ${{ needs.publish.outputs.GITHUB_SHA_SHORT }}
      revision-core-fraction: 25
      container-name: ${{ needs.publish.outputs.APP_NAME }}
    secrets: inherit

  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR name
        id: branch
        run: |
          echo PULL_REQUEST_NAME=$(git describe --all  --contains ${{github.GITHUB_SHA}}) >> $GITHUB_OUTPUT
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          MERGE_COMMIT_MESSAGE: "pull request merged automatically"
          MERGE_REQUIRED_APPROVALS: 1
          MERGE_DELETE_BRANCH: true
          MERGE_ERROR_FAIL: true
          PULL_REQUEST: ${{ steps.branch.outputs.PULL_REQUEST_NAME }}
          BASE_BRANCHES: "main"
