name: Rollback

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        type: string
        required: true

jobs:
  tag:
    name: Check tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "🎉 release ref ${{ inputs.tag }}"
      - run: git tag -l | grep -e "v"
      - run: |
          git tag -l | grep -e "${{ inputs.tag }}" || echo "::error::release tag ${{ inputs.tag }} not found" && exit 1

  publish:
    name: Publish
    needs: tag
    uses: ./.github/workflows/publish.yaml
    with:
      ref: ${{ inputs.tag }}
    secrets: inherit

  deployment:
    name: Deploy
    needs:
      - publish
    uses: ./.github/workflows/deploy.yaml
    with:
      target: "Production"
      tag: ${{ needs.publish.outputs.GITHUB_SHA_SHORT }}
      revision-core-fraction: 25
      container-name: ${{ needs.publish.outputs.APP_NAME }}
    secrets: inherit
